# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shipping.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'shipping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshipping.proto\"Q\n\x0fShippingRequest\x12\x16\n\x0e\x64\x65stination_uf\x18\x01 \x01(\t\x12\x11\n\tweight_kg\x18\x02 \x01(\x01\x12\x13\n\x0border_value\x18\x03 \x01(\x01\"\x87\x01\n\x10ShippingResponse\x12\x16\n\x0e\x64\x65stination_uf\x18\x01 \x01(\t\x12\x1a\n\x12\x64\x65stination_region\x18\x02 \x01(\t\x12\x16\n\x0eshipping_price\x18\x03 \x01(\x01\x12\x16\n\x0e\x65stimated_days\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t2K\n\x0fShippingService\x12\x38\n\x11\x43\x61lculateShipping\x12\x10.ShippingRequest\x1a\x11.ShippingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shipping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHIPPINGREQUEST']._serialized_start=18
  _globals['_SHIPPINGREQUEST']._serialized_end=99
  _globals['_SHIPPINGRESPONSE']._serialized_start=102
  _globals['_SHIPPINGRESPONSE']._serialized_end=237
  _globals['_SHIPPINGSERVICE']._serialized_start=239
  _globals['_SHIPPINGSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
