# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_stream.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'video_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_stream.proto\" \n\x0cVideoRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"\x90\x01\n\nVideoChunk\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63hunk_number\x18\x04 \x01(\x03\x12\x12\n\nsent_bytes\x18\x05 \x01(\x03\x12\x13\n\x0btotal_bytes\x18\x06 \x01(\x03\x12\x14\n\x0c\x63ontent_type\x18\x07 \x01(\t2D\n\x15VideoStreamingService\x12+\n\x0bStreamVideo\x12\r.VideoRequest\x1a\x0b.VideoChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=22
  _globals['_VIDEOREQUEST']._serialized_end=54
  _globals['_VIDEOCHUNK']._serialized_start=57
  _globals['_VIDEOCHUNK']._serialized_end=201
  _globals['_VIDEOSTREAMINGSERVICE']._serialized_start=203
  _globals['_VIDEOSTREAMINGSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
