# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_upload.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'video_upload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_upload.proto\"m\n\nVideoChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63hunk_number\x18\x03 \x01(\x03\x12\x13\n\x0btotal_bytes\x18\x04 \x01(\x03\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\"|\n\rUploadSummary\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x17\n\x0f\x63hunks_received\x18\x02 \x01(\x03\x12\x1c\n\x14total_bytes_received\x18\x03 \x01(\x03\x12\x11\n\tvideo_url\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t2B\n\x12VideoUploadService\x12,\n\x0bUploadVideo\x12\x0b.VideoChunk\x1a\x0e.UploadSummary(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_upload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOCHUNK']._serialized_start=22
  _globals['_VIDEOCHUNK']._serialized_end=131
  _globals['_UPLOADSUMMARY']._serialized_start=133
  _globals['_UPLOADSUMMARY']._serialized_end=257
  _globals['_VIDEOUPLOADSERVICE']._serialized_start=259
  _globals['_VIDEOUPLOADSERVICE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
